// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Petuno.Infrastructure.Data;

#nullable disable

namespace Petuno.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PetunoDbContext))]
    [Migration("20260819051631_AddStoryToPet")]
    partial class AddStoryToPet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Petuno.Core.Entities.AdoptionApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AdoptionPetId")
                        .HasColumnType("uuid")
                        .HasColumnName("adoption_pet_id");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_id");

                    b.Property<string>("ApplicantNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("applicant_notes");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_adoption_applications");

                    b.HasIndex("AdoptionPetId")
                        .HasDatabaseName("ix_adoption_applications_adoption_pet_id");

                    b.HasIndex("ApplicantId")
                        .HasDatabaseName("ix_adoption_applications_applicant_id");

                    b.ToTable("adoption_applications", (string)null);
                });

            modelBuilder.Entity("Petuno.Core.Entities.AdoptionPet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Age")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("age");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("breed");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("FoundationId")
                        .HasColumnType("uuid")
                        .HasColumnName("foundation_id");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("size");

                    b.Property<bool>("SpecialNeeds")
                        .HasColumnType("boolean")
                        .HasColumnName("special_needs");

                    b.Property<string>("SpecialNeedsDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("special_needs_description");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("species");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<string>("Story")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("story");

                    b.HasKey("Id")
                        .HasName("pk_adoption_pets");

                    b.HasIndex("FoundationId")
                        .HasDatabaseName("ix_adoption_pets_foundation_id");

                    b.ToTable("adoption_pets", (string)null);
                });

            modelBuilder.Entity("Petuno.Core.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("integer")
                        .HasColumnName("battery_level");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier");

                    b.Property<DateTime?>("LastConnection")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_connection");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_devices");

                    b.HasIndex("PetId")
                        .HasDatabaseName("ix_devices_pet_id");

                    b.ToTable("devices", (string)null);
                });

            modelBuilder.Entity("Petuno.Core.Entities.Foundation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Nit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_foundations");

                    b.HasIndex("Nit")
                        .IsUnique()
                        .HasDatabaseName("ix_foundations_nit")
                        .HasFilter("nit IS NOT NULL");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_foundations_user_id");

                    b.ToTable("foundations", (string)null);
                });

            modelBuilder.Entity("Petuno.Core.Entities.MedicalRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly?>("DateAdministered")
                        .HasColumnType("date")
                        .HasColumnName("date_administered");

                    b.Property<DateOnly?>("DateDue")
                        .HasColumnType("date")
                        .HasColumnName("date_due");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_medical_records");

                    b.HasIndex("PetId")
                        .HasDatabaseName("ix_medical_records_pet_id");

                    b.ToTable("medical_records", (string)null);
                });

            modelBuilder.Entity("Petuno.Core.Entities.ModuleConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("EnabledForAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled_for_admin");

                    b.Property<bool>("EnabledForFoundation")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled_for_foundation");

                    b.Property<bool>("EnabledForOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled_for_owner");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module_name");

                    b.HasKey("Id")
                        .HasName("pk_module_configs");

                    b.HasIndex("ModuleName")
                        .IsUnique()
                        .HasDatabaseName("ix_module_configs_module_name");

                    b.ToTable("module_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            EnabledForAdmin = true,
                            EnabledForFoundation = true,
                            EnabledForOwner = true,
                            ModuleName = "SOS"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            EnabledForAdmin = true,
                            EnabledForFoundation = true,
                            EnabledForOwner = true,
                            ModuleName = "Adopciones"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            EnabledForAdmin = true,
                            EnabledForFoundation = true,
                            EnabledForOwner = true,
                            ModuleName = "Mascotas Perdidas"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            EnabledForAdmin = true,
                            EnabledForFoundation = false,
                            EnabledForOwner = true,
                            ModuleName = "Dispositivos"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            EnabledForAdmin = true,
                            EnabledForFoundation = true,
                            EnabledForOwner = true,
                            ModuleName = "Veterinarias"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            EnabledForAdmin = true,
                            EnabledForFoundation = true,
                            EnabledForOwner = true,
                            ModuleName = "Comunidad"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            EnabledForAdmin = true,
                            EnabledForFoundation = true,
                            EnabledForOwner = true,
                            ModuleName = "Dashboard"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            EnabledForAdmin = true,
                            EnabledForFoundation = true,
                            EnabledForOwner = true,
                            ModuleName = "Mis Mascotas"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            EnabledForAdmin = true,
                            EnabledForFoundation = true,
                            EnabledForOwner = true,
                            ModuleName = "Notificaciones"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            EnabledForAdmin = true,
                            EnabledForFoundation = true,
                            EnabledForOwner = true,
                            ModuleName = "Configuracion"
                        });
                });

            modelBuilder.Entity("Petuno.Core.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("breed");

                    b.Property<string>("Characteristics")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("characteristics");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Microchip")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("microchip");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PetunoId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("petuno_id");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("species");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<string>("Story")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("story");

                    b.HasKey("Id")
                        .HasName("pk_pets");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_pets_owner_id");

                    b.HasIndex("PetunoId")
                        .IsUnique()
                        .HasDatabaseName("ix_pets_petuno_id");

                    b.ToTable("pets", (string)null);
                });

            modelBuilder.Entity("Petuno.Core.Entities.PetSpecies", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_pet_species");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pet_species_name");

                    b.ToTable("pet_species", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555551"),
                            Name = "Perro"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555552"),
                            Name = "Gato"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555553"),
                            Name = "Ave"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555554"),
                            Name = "Conejo"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555555"),
                            Name = "Caballo"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555556"),
                            Name = "Vaca"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555557"),
                            Name = "Cerdo"
                        },
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-555555555558"),
                            Name = "Otro"
                        });
                });

            modelBuilder.Entity("Petuno.Core.Entities.PrivacySettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("AllowAnonymousContact")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_anonymous_contact");

                    b.Property<bool>("AllowSightings")
                        .HasColumnType("boolean")
                        .HasColumnName("allow_sightings");

                    b.Property<Guid>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<bool>("ShowAge")
                        .HasColumnType("boolean")
                        .HasColumnName("show_age");

                    b.Property<bool>("ShowBreed")
                        .HasColumnType("boolean")
                        .HasColumnName("show_breed");

                    b.Property<bool>("ShowLocation")
                        .HasColumnType("boolean")
                        .HasColumnName("show_location");

                    b.Property<bool>("ShowMedical")
                        .HasColumnType("boolean")
                        .HasColumnName("show_medical");

                    b.Property<bool>("ShowName")
                        .HasColumnType("boolean")
                        .HasColumnName("show_name");

                    b.HasKey("Id")
                        .HasName("pk_privacy_settings");

                    b.HasIndex("PetId")
                        .IsUnique()
                        .HasDatabaseName("ix_privacy_settings_pet_id");

                    b.ToTable("privacy_settings", (string)null);
                });

            modelBuilder.Entity("Petuno.Core.Entities.Sighting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<Guid?>("PetId")
                        .HasColumnType("uuid")
                        .HasColumnName("pet_id");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_url");

                    b.Property<string>("ReporterContact")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("reporter_contact");

                    b.Property<DateTime>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_sightings");

                    b.HasIndex("PetId")
                        .HasDatabaseName("ix_sightings_pet_id");

                    b.ToTable("sightings", (string)null);
                });

            modelBuilder.Entity("Petuno.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Petuno.Core.Entities.AdoptionApplication", b =>
                {
                    b.HasOne("Petuno.Core.Entities.AdoptionPet", "AdoptionPet")
                        .WithMany("Applications")
                        .HasForeignKey("AdoptionPetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adoption_applications_adoption_pets_adoption_pet_id");

                    b.HasOne("Petuno.Core.Entities.User", "Applicant")
                        .WithMany("AdoptionApplications")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adoption_applications_users_applicant_id");

                    b.Navigation("AdoptionPet");

                    b.Navigation("Applicant");
                });

            modelBuilder.Entity("Petuno.Core.Entities.AdoptionPet", b =>
                {
                    b.HasOne("Petuno.Core.Entities.Foundation", "Foundation")
                        .WithMany("AdoptionPets")
                        .HasForeignKey("FoundationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_adoption_pets_foundations_foundation_id");

                    b.Navigation("Foundation");
                });

            modelBuilder.Entity("Petuno.Core.Entities.Device", b =>
                {
                    b.HasOne("Petuno.Core.Entities.Pet", "Pet")
                        .WithMany("Devices")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_devices_pets_pet_id");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Petuno.Core.Entities.Foundation", b =>
                {
                    b.HasOne("Petuno.Core.Entities.User", "User")
                        .WithOne("Foundation")
                        .HasForeignKey("Petuno.Core.Entities.Foundation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_foundations_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Petuno.Core.Entities.MedicalRecord", b =>
                {
                    b.HasOne("Petuno.Core.Entities.Pet", "Pet")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medical_records_pets_pet_id");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Petuno.Core.Entities.Pet", b =>
                {
                    b.HasOne("Petuno.Core.Entities.User", "Owner")
                        .WithMany("Pets")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pets_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Petuno.Core.Entities.PrivacySettings", b =>
                {
                    b.HasOne("Petuno.Core.Entities.Pet", "Pet")
                        .WithOne("PrivacySettings")
                        .HasForeignKey("Petuno.Core.Entities.PrivacySettings", "PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_privacy_settings_pets_pet_id");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Petuno.Core.Entities.Sighting", b =>
                {
                    b.HasOne("Petuno.Core.Entities.Pet", "Pet")
                        .WithMany("Sightings")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sightings_pets_pet_id");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("Petuno.Core.Entities.AdoptionPet", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("Petuno.Core.Entities.Foundation", b =>
                {
                    b.Navigation("AdoptionPets");
                });

            modelBuilder.Entity("Petuno.Core.Entities.Pet", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("MedicalRecords");

                    b.Navigation("PrivacySettings");

                    b.Navigation("Sightings");
                });

            modelBuilder.Entity("Petuno.Core.Entities.User", b =>
                {
                    b.Navigation("AdoptionApplications");

                    b.Navigation("Foundation");

                    b.Navigation("Pets");
                });
#pragma warning restore 612, 618
        }
    }
}
